language: php

php:
  - 7.2

notifications:
  email: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
    - node_modules
    - $HOME/vendor

env:
  global:
  - WP_VERSION=latest
